/* Generated By:JJTree&JavaCC: Do not edit this line. LureParserConstants.java */
package forkbomb.frontend;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LureParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IGNORE = 1;
  /** RegularExpression Id. */
  int NEWLINE = 2;
  /** RegularExpression Id. */
  int LINECOMMENT = 3;
  /** RegularExpression Id. */
  int END = 4;
  /** RegularExpression Id. */
  int IF = 5;
  /** RegularExpression Id. */
  int THEN = 6;
  /** RegularExpression Id. */
  int ELSE = 7;
  /** RegularExpression Id. */
  int LOOP = 8;
  /** RegularExpression Id. */
  int WHILE = 9;
  /** RegularExpression Id. */
  int DO = 10;
  /** RegularExpression Id. */
  int BREAK = 11;
  /** RegularExpression Id. */
  int ASSIGN = 12;
  /** RegularExpression Id. */
  int FN = 13;
  /** RegularExpression Id. */
  int FUN = 14;
  /** RegularExpression Id. */
  int FUNC = 15;
  /** RegularExpression Id. */
  int FUNCTION = 16;
  /** RegularExpression Id. */
  int STAB = 17;
  /** RegularExpression Id. */
  int NUMBER = 18;
  /** RegularExpression Id. */
  int DIGIT = 19;
  /** RegularExpression Id. */
  int QUOTE = 20;
  /** RegularExpression Id. */
  int IDENTIFIER = 21;
  /** RegularExpression Id. */
  int STRING_CHAR = 22;
  /** RegularExpression Id. */
  int ENDQUOTE = 23;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int STRING_STATE = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<IGNORE>",
    "\"\\n\"",
    "<LINECOMMENT>",
    "\"end\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"loop\"",
    "\"while\"",
    "\"do\"",
    "\"break\"",
    "\":=\"",
    "\"fn\"",
    "\"fun\"",
    "\"func\"",
    "\"function\"",
    "\"->\"",
    "<NUMBER>",
    "<DIGIT>",
    "\"\\\'\"",
    "<IDENTIFIER>",
    "<STRING_CHAR>",
    "<ENDQUOTE>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
  };

}
