/* Generated By:JavaCC: Do not edit this line. LureParserVisitor.java Version 5.0 */
package forkbomb.frontend;

public interface LureParserVisitor
{
  public Object visit(SimpleNode node, Object data);
}
/* JavaCC - OriginalChecksum=de2a91f3da4e5db422d87833eba5407a (do not edit this line) */
