/* Generated By:JavaCC: Do not edit this line. LureParserTreeConstants.java Version 5.0 */
package forkbomb.frontend;

public interface LureParserTreeConstants
{
  public int JJTSCRIPT = 0;
  public int JJTVOID = 1;
  public int JJTCONDITIONALEXPRESSION = 2;
  public int JJTLOOPEXPRESSION = 3;
  public int JJTWHILEEXPRESSION = 4;
  public int JJTBREAKEXPRESSION = 5;
  public int JJTSTRING = 6;
  public int JJTASSIGNMENTEXPRESSION = 7;
  public int JJTFUNCTIONSTART = 8;
  public int JJTFUNCTIONLITERALEXPRESSION = 9;
  public int JJTEXPRESSION = 10;
  public int JJTARGUMENTLIST = 11;
  public int JJTFUNCTIONINVOCATIONEXPRESSION = 12;


  public String[] jjtNodeName = {
    "Script",
    "void",
    "ConditionalExpression",
    "LoopExpression",
    "WhileExpression",
    "BreakExpression",
    "String",
    "AssignmentExpression",
    "FunctionStart",
    "FunctionLiteralExpression",
    "Expression",
    "ArgumentList",
    "FunctionInvocationExpression",
  };
}
/* JavaCC - OriginalChecksum=cf37cfe1f99de991bc74c1743941bae6 (do not edit this line) */
